### ISSUE TITLE
what does this mean (fcl 19 FRSM-4.0.00-1.11.2)

### ISSUE THREAD

**Issue by hunnybunny21** [Fexcraft/Minecraft-Stuff#15]
Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl)
Caused by: java.lang.NullPointerException
	at net.fexcraft.mod.lib.network.Validator.initialize(Validator.java:60)

fcl 20 makes my client crash

**Comment by hunnybunny21** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.2.8.1.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  LoadingPlugin (Quark-r1.2-87.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/21/17 10:56 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl)
Caused by: java.lang.NullPointerException
	at net.fexcraft.mod.lib.network.Validator.initialize(Validator.java:60)
	at net.fexcraft.mod.lib.network.Validator.initialize(Validator.java:35)
	at net.fexcraft.mod.lib.FCL.postInit(FCL.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1399356560 bytes (1334 MB) / 2758279168 bytes (2630 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2259 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2259-universal.jar) 
	UCHIJ	forge{13.20.0.2259} [Minecraft Forge] (forge-1.11.2-13.20.0.2259-universal.jar) 
	UCHIJ	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJ	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCHIJ	quark{r1.2-87} [Quark] (Quark-r1.2-87.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCHIJ	blockarmor{2.3} [Block Armor] (BlockArmor-1.11.2-2.3.jar) 
	UCHIJ	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJ	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJ	chesttransporter{2.7.0} [Chest Transporter] (ChestTransporter-1.11.2-2.7.0.jar) 
	UCHIJ	dsurround{3.2.8.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.2.8.1.jar) 
	UCHIJ	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar) 
	UCHIJ	emeraldpack{1.0.0} [Emerald Pack+] (Emerald Pack+.jar) 
	UCHIJ	fairylights{2.0.6} [Fairy Lights] (fairylights-2.0.6-1.11.jar) 
	UCHIJ	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIE	fcl{XI.19} [Fexcraft Common Library] (Fexcraft Common Library-XI.19-1.11.2.jar) 
	UCHIE	frsm{4.0.00} [Fex's Random Stuff Mod] (FRSM-4.0.00-1.11.2.jar) 
	UCHIJ	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJ	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJ	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJ	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJ	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJ	minecolonies{1.11-0.6.3113} [MineColonies] (minecolonies-universal-1.11-0.6.3113.jar) 
	UCHIJ	missing_pieces{4.1.2} [Missing Pieces] (missing_pieces-1.11.2-4.1.2.jar) 
	UCHIJ	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJ	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.11).jar) 
	UCHIJ	obsidianpack{1.0.0} [Obsidian Pack+] (Obsidian Pack+.jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJ	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHIJ	prefab{1.2.0.6} [Prefab] (prefab-1.2.0.6.jar) 
	UCHIJ	randomthings{3.8} [Random Things] (RandomThings-MC1.11.2-3.8.jar) 
	UCHIJ	reccomplex{1.2.10} [Recurrent Complex] (RecurrentComplex-1.2.10.jar) 
	UCHIJ	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJ	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-65.jar) 
	UCHIJ	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJ	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJ	staircutters{1.0} [staircutters] (Staircutters-1.11-0.1.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.2.8.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
IvToolkit (IvToolkit-1.3.2.1.jar)
  
LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  lumien.randomthings.asm.ClassTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
LoadingPlugin (Quark-r1.2-87.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Fexcraft** [comment]
I'll look into it, might have something to do with yesterday's website update, since that line of code usually connects to the (web) server.

**Comment by Fexcraft** [comment]
Well, it seems it's an naming error in the `json` object the web server is sending back to the client which expects something else.
Might be able to fix it remotely.

**Comment by Fexcraft** [comment]
Found the issue, there was an missing line of code on the web-server which caused it to send the wrong response back to the client (which the client didn't expect/want) and thus caused the crash, should be fixed by now.
