### ISSUE TITLE
server crash and fcl 24 server log (is it bad?)

### ISSUE THREAD

**Issue by hunnybunny21** [Fexcraft/Minecraft-Stuff#16]
fcl 19 crash server

fcl 24
after i join 
it says

[17:08:36] [Server thread/INFO]: [STDERR]: java.lang.IllegalStateException: Not a JSON Object: null
[17:08:36] [Server thread/INFO]: [STDERR]:      at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.util.json.JsonUtil.getObjectFromInputStream(JsonUtil.java:571)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.request(Network.java:69)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network$ServerValidator.isDonator(Network.java:312)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:163)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:171)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.SimpleUpdateHandler$EventHandler.onJoin(SimpleUpdateHandler.java:139)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_EventHandler_onJoin_PlayerLoggedInEvent.invoke(.dynamic)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:568)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:214)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[17:08:36] [Server thread/INFO]: [STDERR]:      at java.lang.Thread.run(Unknown Source)
[17:08:36] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.request(Network.java:69)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network$ServerValidator.isDonator(Network.java:312)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:163)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:171)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.fexcraft.mod.lib.network.SimpleUpdateHandler$EventHandler.onJoin(SimpleUpdateHandler.java:139)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_EventHandler_onJoin_PlayerLoggedInEvent.invoke(.dynamic)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:568)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:214)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[17:08:36] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[17:08:36] [Server thread/INFO]: [STDERR]:      at java.lang.Thread.run(Unknown Source)

**Comment by Fexcraft** [comment]
Does the error still persist?
I was updating/editing the website and server today for some hours to add SSL.
But if it still crashes now, I'll look into it.

**Comment by hunnybunny21** [comment]
fcl 19 still crashes 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  IvToolkit (IvToolkit-1.3.2.1.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 4/14/17 5:41 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fexcraft Common Library (fcl)
Caused by: java.lang.NullPointerException
	at net.fexcraft.mod.lib.network.DonorValidator.getList(DonorValidator.java:37)
	at net.fexcraft.mod.lib.network.DonorValidator.initialize(DonorValidator.java:27)
	at net.fexcraft.mod.lib.FCL.postInit(FCL.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1226653280 bytes (1169 MB) / 2539651072 bytes (2422 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2251 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2251-universal.jar) 
	UCHIJ	forge{13.20.0.2251} [Minecraft Forge] (forge-1.11.2-13.20.0.2251-universal.jar) 
	UCHIJ	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJ	backpacks16840{3.1.8} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.8.jar) 
	UCHIJ	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCHIJ	babyanimals{1.11} [Baby Animals Model Swapper] (BabyAnimals-1.11.jar) 
	UCHIJ	blockarmor{2.4.2} [Block Armor] (BlockArmor-1.11.2-2.4.2.jar) 
	UCHIJ	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJ	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJ	chesttransporter{2.7.5} [Chest Transporter] (ChestTransporter-1.11.2-2.7.5.jar) 
	UCHIJ	clockhud{1.3.3} [Clock HUD] (ClockHUD-1.11-1.3.3.jar) 
	UCHIJ	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.11.2.jar) 
	UCHIJ	dsurround{3.3.3.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.3.1.jar) 
	UCHIJ	eggs{1.0} [Eat the Eggs!] (EM3R50N-EatTheEggs-1.11.2-13.20.0.2201.jar) 
	UCHIJ	emeraldpack{1.0.0} [Emerald Pack+] (Emerald Pack+.jar) 
	UCHIJ	fairylights{2.0.6} [Fairy Lights] (fairylights-2.0.6-1.11.jar) 
	UCHIJ	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIE	fcl{XI.19} [Fexcraft Common Library] (Fexcraft Common Library-XI.19-1.11.2.jar) 
	UCHIE	frsm{4.0.00} [Fex's Random Stuff Mod] (FRSM-4.0.00-1.11.2.jar) 
	UCHIJ	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJ	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJ	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJ	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJ	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJ	minecolonies{1.11-0.6.3360} [MineColonies] (minecolonies-universal-1.11-0.6.3360.jar) 
	UCHIJ	missing_pieces{4.1.2} [Missing Pieces] (missing_pieces-1.11.2-4.1.2.jar) 
	UCHIJ	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJ	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.11).jar) 
	UCHIJ	obsidianpack{1.0.0} [Obsidian Pack+] (Obsidian Pack+.jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJ	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHIJ	prefab{1.2.0.6} [Prefab] (prefab-1.2.0.6.jar) 
	UCHIJ	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	UCHIJ	reccomplex{1.2.10} [Recurrent Complex] (RecurrentComplex-1.2.10.jar) 
	UCHIJ	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJ	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-67.jar) 
	UCHIJ	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJ	ruins{16.5} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJ	staircutters{1.0} [staircutters] (Staircutters-1.11-0.1.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.2} [Storage Drawers] (StorageDrawers-1.11.2-4.2.2.jar) 
	UCHIJ	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJ	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
IvToolkit (IvToolkit-1.3.2.1.jar)
  
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Fexcraft** [comment]
What about xi.24?
If it works you could use it then.

**Comment by hunnybunny21** [comment]
fcl 24 works but
every time i join it says
(is this bad?)

[17:08:36] [Server thread/INFO]: [STDERR]: java.lang.IllegalStateException: Not a JSON Object: null
[17:08:36] [Server thread/INFO]: [STDERR]: at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.util.json.JsonUtil.getObjectFromInputStream(JsonUtil.java:571)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.request(Network.java:69)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network$ServerValidator.isDonator(Network.java:312)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:163)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:171)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.SimpleUpdateHandler$EventHandler.onJoin(SimpleUpdateHandler.java:139)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_EventHandler_onJoin_PlayerLoggedInEvent.invoke(.dynamic)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:568)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:214)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[17:08:36] [Server thread/INFO]: [STDERR]: at java.lang.Thread.run(Unknown Source)
[17:08:36] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.request(Network.java:69)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network$ServerValidator.isDonator(Network.java:312)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:163)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.Network.isDonator(Network.java:171)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.fexcraft.mod.lib.network.SimpleUpdateHandler$EventHandler.onJoin(SimpleUpdateHandler.java:139)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_EventHandler_onJoin_PlayerLoggedInEvent.invoke(.dynamic)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:568)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:214)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[17:08:36] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[17:08:36] [Server thread/INFO]: [STDERR]: at java.lang.Thread.run(Unknown Source)

**Comment by Fexcraft** [comment]
As long it doesn't crash, nah.

The error message says that getting a JSON file from the webserver failed (returned null?).
The function for which that JSON would be any useful isn't used anyways currently.
So no, as of now, it isn't bad.

**Comment by hunnybunny21** [comment]
ok
fcl 19 wont be changed to fix the crash ?

**Comment by Fexcraft** [comment]
If I would edit anything in 19, it wouldn't be 19 anymore ;)
next version would be 25, since latest is 24.

**Comment by hunnybunny21** [comment]
obviously
but last time this happened
you did something
and it worked again

**Comment by Fexcraft** [comment]
Well, just happens that I actually might have done it again, lel.

While trying to backport some mod to 1.10.2, noticed that multiple mods were crashing too due to nearly exactly the same error.
Edited the WebServer config and it works again.
So ye.. the xi.19 version might work again.

**Comment by hunnybunny21** [comment]
yes i can confirm that fcl 19 works now
server started successfully
thank you

so i guess there some sort of conflict whenever  three is a new fcl or something to do with the website communication
(i dont have any knowledge on what happens when a server starts and the communications with website)

**Comment by Fexcraft** [comment]
Well, it's rather related to that that I setup today the SSL stuff for my website.
So that browsers like e.g. Chrome don't complain that the "connection" is **not secure**.
(last time there was an protocol error if I recall right what broke xi.19)

That though broke the communication with the mods, which simply need to access a public JSON file
with the normal "HTTP" protocol, and not the **secure** "HTTPS".
So I added an exception for the address/es where the mods are asking for their data and it works again.

(the json files/objects the mods are requesting the server for, contain simple data like: if there is an update available, which is the new version, sometimes mod specific data, and also info if the current player is a donator (on server it checks a list), etc.)
Here e.g. the JSON for FCL alone: http://fexcraft.net/minecraft/fcl/request.fn?mode=requestdata&modid=fcl
